services:
  - type: web
    name: coas
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: LAMBDA_EXECUTION_ROLE_ARN
        sync: false
