cookie:
  expiry_days: 7
  key: coms_secret_key_change_in_prod
  name: coms_auth
credentials:
  usernames:
    admin:
      email: admin@coms.ai
      name: Admin User
      password: $2b$12$UDp35lNMQIajZlgn2eY.ouIrWIxX9i6og8pYbxIZy0buos18dHj2i
      role: admin
    dev:
      email: dev@coms.ai
      name: Developer
      password: $2b$12$I3YOzBLoH3HbCQCY4IuEl.ZlKiSYmVCvL8d/c//xHyRSkmB8BB0DC
      role: developer
    devlead:
      email: devlead@coms.ai
      name: Dev Lead
      password: $2b$12$w5RYSuzyVedoOTmGOtJ4Oewn28BSpcO.cmkfUDplX0R0HBxigS33y
      role: dev-lead
